In [33]:
import pandas as pd
import numpy as np

In [54]:
df = pd.DataFrame({"id" : [1,2,3,4,5,6,7,8,9,10,11,12,13,14],
                   "age" : ["youth","youth","middle_aged","senior","senior","senior","middle_aged","youth","youth","senior","youth","middle_aged","middle_aged","senior"],
                   "income" : ["high","high","high","medium","low","low","low","medium","low","medium","medium","medium","high","medium"],
                   "student" : ["no","no","no","no","yes","yes","yes","no","yes","yes","yes","no","yes","no"],
                   "credit_rating" : ["fair","excellent","fair","fair","fair","excellent","excellent","fair","fair","fair","excellent","excellent","fair","excellent"],
                   "buys_computer" :  ["no","no","yes","yes","yes","no","yes","no","yes","yes","yes","yes","yes","no"]
                  })

In [55]:
df

    id          age  income student credit_rating buys_computer
0    1        youth    high      no          fair            no
1    2        youth    high      no     excellent            no
2    3  middle_aged    high      no          fair           yes
3    4       senior  medium      no          fair           yes
4    5       senior     low     yes          fair           yes
5    6       senior     low     yes     excellent            no
6    7  middle_aged     low     yes     excellent           yes
7    8        youth  medium      no          fair            no
8    9        youth     low     yes          fair           yes
9   10       senior  medium     yes          fair           yes
10  11        youth  medium     yes     excellent           yes
11  12  middle_aged  medium      no     excellent           yes
12  13  middle_aged    high     yes          fair           yes
13  14       senior  medium      no     excellent            no

Removing id column because it has unique values

In [56]:
df = df.drop(columns = "id" ,axis = 1)

In [57]:
df

            age  income student credit_rating buys_computer
0         youth    high      no          fair            no
1         youth    high      no     excellent            no
2   middle_aged    high      no          fair           yes
3        senior  medium      no          fair           yes
4        senior     low     yes          fair           yes
5        senior     low     yes     excellent            no
6   middle_aged     low     yes     excellent           yes
7         youth  medium      no          fair            no
8         youth     low     yes          fair           yes
9        senior  medium     yes          fair           yes
10        youth  medium     yes     excellent           yes
11  middle_aged  medium      no     excellent           yes
12  middle_aged    high     yes          fair           yes
13       senior  medium      no     excellent            no

In [37]:
# df["age"] = df["age"].map({"youth" : 0,"middle_aged" : 1,"senior" : 2})
# df["income"] = df["income"].map({"high" : 1,"medium" : 1,"low" : 0})
# df["student"] = df["student"].map({"no" : 0,"yes" : 1})
# df["credit_rating"] = df["credit_rating"].map({"fair" : 0,"excellent" : 1})
# df['buys_computer'] = df["buys_computer"].map({"no" : 0 , "yes" : 1})

In [38]:
# df

    age  income  student  credit_rating  buys_computer
0     0       1        0              0              0
1     0       1        0              1              0
2     1       1        0              0              1
3     2       1        0              0              1
4     2       0        1              0              1
5     2       0        1              1              0
6     1       0        1              1              1
7     0       1        0              0              0
8     0       0        1              0              1
9     2       1        1              0              1
10    0       1        1              1              1
11    1       1        0              1              1
12    1       1        1              0              1
13    2       1        0              1              0

In [58]:
from sklearn.preprocessing import LabelEncoder

In [59]:
le = LabelEncoder()

for col in df.columns:
    df[col] = le.fit_transform(df[col])

In [60]:
df

    age  income  student  credit_rating  buys_computer
0     2       0        0              1              0
1     2       0        0              0              0
2     0       0        0              1              1
3     1       2        0              1              1
4     1       1        1              1              1
5     1       1        1              0              0
6     0       1        1              0              1
7     2       2        0              1              0
8     2       1        1              1              1
9     1       2        1              1              1
10    2       2        1              0              1
11    0       2        0              0              1
12    0       0        1              1              1
13    1       2        0              0              0

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X = df.drop("buys_computer",axis = 1)
y = df["buys_computer"]

In [63]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [64]:
print("\nTraining Samples :", len(X_train))
print("Testing Samples :", len(X_test))

Training Samples : 11
Testing Samples : 3

In [65]:
from sklearn.naive_bayes import GaussianNB

In [66]:
model = GaussianNB()

In [67]:
model.fit(X_train, y_train)

GaussianNB()

In [68]:
pred = model.predict(X_test)

In [69]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score

In [70]:
accuracy = accuracy_score(y_test,pred)

In [71]:
print(f"Accuracy : {accuracy}")

Accuracy : 0.6666666666666666

In [72]:
print("\nConfusion Matrix")
print(confusion_matrix(y_test, pred))

Confusion Matrix
[[0 1]
 [0 2]]

In [73]:
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test,pred)
print("Precision:", round(precision,4))
print("Recall   :", round(recall,4))
print("F1 Score :", round(f1,4))

Precision: 0.6667
Recall   : 1.0
F1 Score : 0.8

In [74]:
print("\nClassification Report:\n", classification_report(y_test,pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.67      1.00      0.80         2

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Without the Built-in functions

Finding the unique class Labels

In [75]:
classes = y_train.unique()
print(classes)

[1 0]

In [76]:
prior = {}

for c in classes:
    prior[c] = len(y_train[y_train == c]) / len(y_train)

print(prior)

{np.int64(1): 0.6363636363636364, np.int64(0): 0.36363636363636365}

In [81]:
for c in classes:
  class_rows = X_train[y_train == c]
  print(class_rows)

    age  income  student  credit_rating
12    0       0        1              1
8     2       1        1              1
2     0       0        0              1
4     1       1        1              1
10    2       2        1              0
3     1       2        0              1
6     0       1        1              0
    age  income  student  credit_rating
5     1       1        1              0
1     2       0        0              0
13    1       2        0              0
7     2       2        0              1

In [86]:
for col in X_train.columns:
  unique_values = X_train[col].nunique()
  print(unique_values)
  # used to count the number of unique (distinct) values in a dataset

3
3
2
2

In [90]:
X_test

    age  income  student  credit_rating
9     1       2        1              1
11    0       2        0              0
0     2       0        0              1

In [92]:
len(X_test)

3

In [87]:
import numpy as np

# Unique classes
classes = y_train.unique()

# Prior probabilities
prior = {}

for c in classes:
    prior[c] = len(y_train[y_train == c]) / len(y_train)


# Prediction Function
def predict(sample):

    probabilities = {}

    for c in classes:

        # Start with Prior Probability
        prob = prior[c]

        print(f"\nClass = {c}")
        print("Prior =", prior[c])

        # Multiply conditional probabilities
        for col in X_train.columns:

            # Number of rows of class c
            class_rows = X_train[y_train == c]

            # Count of feature value in class
            numerator = len(class_rows[class_rows[col] == sample[col]])

            # Total rows in class
            denominator = len(class_rows)

            # Laplace Smoothing
            unique_values = X_train[col].nunique()

            # Adding 1 in numerator because if the numerator become 0 the entire probability becomes 0
            conditional = (numerator + 1) / (denominator + unique_values)

            print(f"P({col}={sample[col]}|{c}) = ({numerator}+1)/({denominator}+{unique_values}) = {conditional:.4f}")

            prob *= conditional

        probabilities[c] = prob

        print("Final Probability =", prob)

    return max(probabilities, key=probabilities.get)

In [96]:
p = []

for c in range(len(X_test)):
    sample = X_test.iloc[c]

    prediction = predict(sample)

    print("\nPrediction =", prediction)

    p.append(prediction)
    print("\n")

Class = 1
Prior = 0.6363636363636364
P(age=1|1) = (2+1)/(7+3) = 0.3000
P(income=2|1) = (2+1)/(7+3) = 0.3000
P(student=1|1) = (5+1)/(7+2) = 0.6667
P(credit_rating=1|1) = (5+1)/(7+2) = 0.6667
Final Probability = 0.025454545454545452

Class = 0
Prior = 0.36363636363636365
P(age=1|0) = (2+1)/(4+3) = 0.4286
P(income=2|0) = (2+1)/(4+3) = 0.4286
P(student=1|0) = (1+1)/(4+2) = 0.3333
P(credit_rating=1|0) = (1+1)/(4+2) = 0.3333
Final Probability = 0.007421150278293135

Prediction = 1



Class = 1
Prior = 0.6363636363636364
P(age=0|1) = (3+1)/(7+3) = 0.4000
P(income=2|1) = (2+1)/(7+3) = 0.3000
P(student=0|1) = (2+1)/(7+2) = 0.3333
P(credit_rating=0|1) = (2+1)/(7+2) = 0.3333
Final Probability = 0.008484848484848484

Class = 0
Prior = 0.36363636363636365
P(age=0|0) = (0+1)/(4+3) = 0.1429
P(income=2|0) = (2+1)/(4+3) = 0.4286
P(student=0|0) = (3+1)/(4+2) = 0.6667
P(credit_rating=0|0) = (3+1)/(4+2) = 0.6667
Final Probability = 0.009894867037724178

Prediction = 0



Class = 1
Prior = 0.6363636363636364
P(age=2|1) = (2+1)/(7+3) = 0.3000
P(income=0|1) = (2+1)/(7+3) = 0.3000
P(student=0|1) = (2+1)/(7+2) = 0.3333
P(credit_rating=1|1) = (5+1)/(7+2) = 0.6667
Final Probability = 0.012727272727272726

Class = 0
Prior = 0.36363636363636365
P(age=2|0) = (2+1)/(4+3) = 0.4286
P(income=0|0) = (1+1)/(4+3) = 0.2857
P(student=0|0) = (3+1)/(4+2) = 0.6667
P(credit_rating=1|0) = (1+1)/(4+2) = 0.3333
Final Probability = 0.00989486703772418

Prediction = 1

In [98]:
print(y_test)

9     1
11    1
0     0
Name: buys_computer, dtype: int64

In [97]:
accuracy = accuracy_score(y_test,p)
print(f"Accuracy : {accuracy}")

Accuracy : 0.3333333333333333

# Categorical Naive Bayes

In [106]:
df = pd.DataFrame({"id" : [1,2,3,4,5,6,7,8,9,10,11,12,13,14],
                   "age" : ["youth","youth","middle_aged","senior","senior","senior","middle_aged","youth","youth","senior","youth","middle_aged","middle_aged","senior"],
                   "income" : ["high","high","high","medium","low","low","low","medium","low","medium","medium","medium","high","medium"],
                   "student" : ["no","no","no","no","yes","yes","yes","no","yes","yes","yes","no","yes","no"],
                   "credit_rating" : ["fair","excellent","fair","fair","fair","excellent","excellent","fair","fair","fair","excellent","excellent","fair","excellent"],
                   "buys_computer" :  ["no","no","yes","yes","yes","no","yes","no","yes","yes","yes","yes","yes","no"]
                  })

In [107]:
from sklearn.model_selection import train_test_split
X = df.drop("buys_computer",axis = 1)
y = df["buys_computer"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

print("\nTraining Samples :", len(X_train))
print("Testing Samples :", len(X_test))

Training Samples : 11
Testing Samples : 3

In [112]:
for c in classes:
  class_rows = X_train[y_train == c]
  print(class_rows)

    id          age  income student credit_rating
12  13  middle_aged    high     yes          fair
8    9        youth     low     yes          fair
2    3  middle_aged    high      no          fair
4    5       senior     low     yes          fair
10  11        youth  medium     yes     excellent
3    4       senior  medium      no          fair
6    7  middle_aged     low     yes     excellent
    id     age  income student credit_rating
5    6  senior     low     yes     excellent
1    2   youth    high      no     excellent
13  14  senior  medium      no     excellent
7    8   youth  medium      no          fair

In [133]:
y_test

9     yes
11    yes
0      no
Name: buys_computer, dtype: object

In [108]:
import pandas as pd
import numpy as np

classes = y_train.unique()

prior = {}

for c in classes:
    prior[c] = len(y_train[y_train == c]) / len(y_train)

print(prior)

{'yes': 0.6363636363636364, 'no': 0.36363636363636365}

In [125]:
def predict(sample):

    probabilities = {}

    for c in classes:

        # Prior Probability
        prob = prior[c]

        # Rows belonging to class c
        class_rows = X_train[y_train == c]

        # Calculate Conditional Probability
        for col in X_train.columns:

            numerator = len(class_rows[class_rows[col] == sample[col]])
            denominator = len(class_rows)

            # Without Laplace Smoothing
            if denominator == 0:
                conditional = 0
            else:
                conditional = numerator / denominator

            print(f"P({col}={sample[col]}|{c}) = ({numerator})/({denominator}) = {conditional:.4f}")

            prob *= conditional

        probabilities[c] = prob

    return max(probabilities, key=probabilities.get)

In [134]:
predictions = []

for i in range(len(X_test)):
    sample = X_test.iloc[i]

    prediction = predict(sample)

    predictions.append(prediction)

    print()
    print(f"Sample {i+1}: Predicted Class = {prediction}")
    print()

P(id=10|yes) = (0)/(7) = 0.0000
P(age=senior|yes) = (2)/(7) = 0.2857
P(income=medium|yes) = (2)/(7) = 0.2857
P(student=yes|yes) = (5)/(7) = 0.7143
P(credit_rating=fair|yes) = (5)/(7) = 0.7143
P(id=10|no) = (0)/(4) = 0.0000
P(age=senior|no) = (2)/(4) = 0.5000
P(income=medium|no) = (2)/(4) = 0.5000
P(student=yes|no) = (1)/(4) = 0.2500
P(credit_rating=fair|no) = (1)/(4) = 0.2500

Sample 1: Predicted Class = yes

P(id=12|yes) = (0)/(7) = 0.0000
P(age=middle_aged|yes) = (3)/(7) = 0.4286
P(income=medium|yes) = (2)/(7) = 0.2857
P(student=no|yes) = (2)/(7) = 0.2857
P(credit_rating=excellent|yes) = (2)/(7) = 0.2857
P(id=12|no) = (0)/(4) = 0.0000
P(age=middle_aged|no) = (0)/(4) = 0.0000
P(income=medium|no) = (2)/(4) = 0.5000
P(student=no|no) = (3)/(4) = 0.7500
P(credit_rating=excellent|no) = (3)/(4) = 0.7500

Sample 2: Predicted Class = yes

P(id=1|yes) = (0)/(7) = 0.0000
P(age=youth|yes) = (2)/(7) = 0.2857
P(income=high|yes) = (2)/(7) = 0.2857
P(student=no|yes) = (2)/(7) = 0.2857
P(credit_rating=fair|yes) = (5)/(7) = 0.7143
P(id=1|no) = (0)/(4) = 0.0000
P(age=youth|no) = (2)/(4) = 0.5000
P(income=high|no) = (1)/(4) = 0.2500
P(student=no|no) = (3)/(4) = 0.7500
P(credit_rating=fair|no) = (1)/(4) = 0.2500

Sample 3: Predicted Class = yes

In [137]:
predictions

['yes', 'yes', 'yes']

In [138]:
print(type(y_test.iloc[0]), y_test.iloc[0])
print(type(predictions[0]), predictions[0])

<class 'str'> yes
<class 'str'> yes

In [135]:
accuracy = accuracy_score(y_test, predictions)

print("Accuracy =", accuracy)

Accuracy = 0.6666666666666666

In [140]:
print("\nConfusion Matrix")
print(confusion_matrix(y_test, predictions))

Confusion Matrix
[[0 1]
 [0 2]]

In [139]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions, pos_label="yes")
recall = recall_score(y_test, predictions, pos_label="yes")
f1 = f1_score(y_test, predictions, pos_label="yes")

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.6666666666666666
Precision: 0.6666666666666666
Recall   : 1.0
F1 Score : 0.8